name: Build FileForge

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # This allows the workflow to create releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Get Version
      id: version
      run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Create bin directory
      run: mkdir -p bin
        
    - name: Build Windows
      run: |
        CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o bin/FileForge_windows.exe FileForge.go
        
    - name: Build Linux
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/FileForge_linux FileForge.go

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: FileForge v${{ steps.version.outputs.version }}
        files: |
          bin/FileForge_windows.exe
          bin/FileForge_linux